### PR TITLE
GH-140: Check commits made from browser file edit

### PR DESCRIPTION
**Pull request by sford**

### CODE REVIEW

**Comment by cbugot-swi** [comment]
Hi @sford, 
First: thanks for the work your are doing in sharing and maintaining this plugin for BitBucket.
I have 2 questions:
1) It seems that the current official version does not check commits when clicking on the Merge button of PRs as well. Do you know if this change will all fix that?
2) Do you have a rough idea on when you'd like to merge this in and deploy into a new version of the plugin? Is there anyway we could help?

**Comment by 1arrow** [comment]
Any idea when this will be released? desperately need it

**Review by 1arrow — APPROVED** [review]
lgtm

**Comment by sford** [comment]
Still pending some testing, but 1.25 SNAPSHOT is available for downloading with this feature:
https://github.com/sford/yet-another-commit-checker/actions/runs/36750102

If anyone wants to test this, let me know how it works.

**Comment by kinglamer** [comment]
Big thanks to @sford  for this PR. I have tested it.
When I try to edit code from web UI, plugin force me to create a new branch and pull request.  This is not very convenient. 

I think it should check if current branch name is correct (compare with branch regex), allow to push commit from web UI directly and check only commit message.

If not, then force to create a new branch

**Comment by sagarb2** [comment]
@sford looks like the 1.25 snapshot has expired. Do you mind sharing the latest snapshot so that we can test this

**Comment by sford** [comment]
Hi @sagarb2 , I am unable right this minute, but can you sync up with @george-vulov regarding this feature?

**Comment by sagarb2** [comment]
@george-vulov can you please help on this feature. We have projects using YACC but we are not able to enable browser editing in Bitbucket due to this. Thanks @sford

**Comment by george-vulov** [comment]
We should have an official version with this fix uploaded to the marketplace within a week.

**Comment by george-vulov** [comment]
The fix for this is now released, see [version 1.25.0 on the YACC Marketplace listing](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions).

@sagarb2

**Pull request closed without merging**
