### PR TITLE
Added ability to validate branch name when the branch is created through the Stash UI

### PR DESCRIPTION
**Pull request by wadahiro**
Currently, 'Branch Name Regex' setting doesn't affect when the branch is created through the Stash UI.
As it is mentioned in issue #31, stash now has an event that is fired before the branch is created in the UI. So I added this event listener that validate branch name.

Note: It requires stash 3.7.0.

### CODE REVIEW

**Comment by wadahiro** [comment]
> The Travis CI build could not complete due to an error

Hmm.. It looks like the sdkrepo of atlassian has problem now... It returns 403 Forbidden.

**Comment by sford** [comment]
Ugh, that is annoying :-( It is affecting my master branch builds too.

I just opened a bug report for AMPS JIRA project: https://ecosystem.atlassian.net/browse/AMPS-1283

**Comment by sford** [comment]
sdkrepo.atlassian.com should be working again :-) it looks like your PR has merge conflicts, want to fix those and that should trigger a new CI build?

**Comment by wadahiro** [comment]
@sford Thank you for reporting to the Atlassian! I'll do rebase against latest master branch soon.

**Comment by wadahiro** [comment]
@sford 
The Travis CI build failed in integration test.

> Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 111.079 sec <<< FAILURE!
> testRepositorySettings(it.com.isroot.stash.plugin.SettingsTest)  Time elapsed: 5.433 sec  <<< ERROR!
> org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM

It looks like a race condition of selenuim test because all tests were passed in local. Could you press "Restart Build" in Travis CI?

**Comment by sford** [comment]
@wadahiro Build passed! I just recently added that selenium test and have noticed it intermittently failing :-( I need to fix it.

Thanks for the PR! I am heading out to go camping for 4 days and won't have internet access until I get back. I will get this merged next week. Thanks!

**Comment by wadahiro** [comment]
@sford  Sure thing. Please enjoy camping! :-)

**Comment by sford** [comment]
@wadahiro Thanks for the PR! Looks good :+1:

**Pull request merged**
